fotoclub/src/Entity/Agenda.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AgendaRepository")
 */
class Agenda
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateCreated;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateUpdated;

    /**
     * @ORM\Column(type="datetime")
     */
    private $eventDate;

    /**
     * @ORM\Column(type="boolean")
     */
    private $enabled;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->dateCreated;
    }

    public function setDateCreated(\DateTimeInterface $dateCreated): self
    {
        $this->dateCreated = $dateCreated;

        return $this;
    }

    public function getDateUpdated(): ?\DateTimeInterface
    {
        return $this->dateUpdated;
    }

    public function setDateUpdated(\DateTimeInterface $dateUpdated): self
    {
        $this->dateUpdated = $dateUpdated;

        return $this;
    }

    public function getEventDate(): ?\DateTimeInterface
    {
        return $this->eventDate;
    }

    public function getFormattedEventDate(): string
    {
        return $this->eventDate->format('d-m-Y');
    }

    public function setEventDate(\DateTimeInterface $eventDate): self
    {
        $this->eventDate = $eventDate;

        return $this;
    }

    public function getEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): self
    {
        $this->enabled = $enabled;

        return $this;
    }
}

fotoclub/src/Controller/AgendaController.php
<?php

namespace App\Controller;

use App\Service\AgendaService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\NewsService;

class AgendaController extends AbstractController
{
    /** @var AgendaService */
    protected $agendaService;

    public function __construct(AgendaService $agendaService)
    {
        $this->agendaService = $agendaService;
    }

    /**
     * @Route("/agenda", name="agenda")
     */
    public function index()
    {
        $futureEvents = $this->agendaService->getFutureEvents();
        $allPastEvents = $this->agendaService->getAllEvents();

        return $this->render('agenda/index.html.twig', [
            'futureEvents' => $futureEvents,
            'events' => $allPastEvents,
        ]);
    }

    /**
     * @Route("/agenda/{year}/{month}", name="monthEvents")
     *
     * @param int $year
     * @param string $month
     * @return Response
     */
    public function month(int $year, string $month)
    {
        $allPastEvents = $news = $this->agendaService->getAllEvents();
        $monthEvents = $this->agendaService->getEventsByMonth($year, $month);

        return $this->render('agenda/month.html.twig', [
            'monthEvents' => $monthEvents,
            'events' => $allPastEvents,
        ]);
    }
}

fotoclub/templates/agenda/_leftNav.html.twig
<aside>
    <ul>
        <li>
            <span>Agenda</span>
            <ul class="second">
                {% for year, itemMonths in agenda %}
                    <li><span>{{ year }}</span></li>
                    <ul class="second">
                        {% for month, items in itemMonths %}
                            <li><a href="{{ path('monthEvents', {year: year, month: month }) }}">{{ month|capitalize }}</a></li>
                        {% endfor %}
                    </ul>
                {% endfor %}
            </ul>
        </li>
    </ul>
</aside>

fotoclub/templates/agenda/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agenda | Fotoclub Uitgeest{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-xs-12 col-sm-3">
            {% include 'agenda/_leftNav.html.twig' with {'agenda': events} %}
        </div>
        <div class="col-xs-12 col-sm-9">
            <div class="row nieuwsPage">
                {% if futureEvents is empty %}
                    <article>
                        <header><h1>Agenda</h1></header>
                        <section><p>Op dit moment staat er niets op de agenda voor de komende periode.</p></section>
                    </article>
                {% endif %}

                {% for years in futureEvents %}
                    {% for months in years %}
                        {% for agendaItem in months %}
                            <article class="partialSize">
                                <header>
                                    <h1>{{ agendaItem.title }}</h1>
                                    <time datetime="{{ agendaItem.formattedEventDate |date('Y-m-d') }}">
                                        {{ agendaItem.formattedEventDate |date('d-m-Y') }}
                                    </time>
                                </header>
                                <section>{{ agendaItem.text|raw }}</section>
                            </article>
                        {% endfor %}
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

fotoclub/templates/agenda/month.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agenda | Fotoclub Uitgeest{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-xs-12 col-sm-3">
            {% include 'agenda/_leftNav.html.twig' with {'agenda': events} %}
        </div>
        <div class="col-xs-12 col-sm-9">
            <div class="row nieuwsPage">
                {% if monthEvents is empty %}
                    <article>
                        <header><h1>Agenda</h1></header>
                        <section><p>Op dit moment staat er niets op de agenda voor de komende periode.</p></section>
                    </article>
                {% endif %}

                {% for agendaItem in monthEvents %}
                    <article class="partialSize">
                        <header>
                            <h1>{{ agendaItem.title }}</h1>
                            <time datetime="{{ agendaItem.eventDate |date('Y-m-d') }}">
                                {{ agendaItem.eventDate |date('d-m-Y') }}
                            </time>
                        </header>
                        <section>{{ agendaItem.text|raw }}</section>
                    </article>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}